baseURL = 'https://GrapentinPsychologicalServices.com/'
googleAnalytics = "G-7Q7YYME1ZS"
languageCode = 'en-us'
title = 'Grapentin Psychological Services'
disableKinds = ["taxonomy", "taxonomyTerm"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
[Params]
  images = ["img/social.png"]
  production = true
  description = "Therapy practice by Andrew Grapentin"